<?php
/**
 *
 * TODO: hook node save pour push tic_geosource
 * hook node update pour update tic_geosource ?
 * cron synchro vers tic_geosource
 * hook push vers tic_geosource a la sauvegarde d'une carte
 *
 */

// DEBUG
function tic_geosource_node_view($node, $v, $e) {
	return;
	module_load_include('inc', 'tic_geosource', 'includes/tic_geosource.utils');
	
	$client = tic_geosource_load_csw_client();
	
	$geoid = $client->getGeoidFromUuid('2b3bbdd1-c1b1-475a-a0c9-6478e1f949f5');
	$client->addMapCategory($geoid);
	die();
	
	$xml = $client->getRecordsModifiedSince(new DateTime('2012-07-08'));
	$uuids = tic_geosource_get_result_uuids($xml);
	
	//var_dump(tic_geosource_record_to_node($records[2])); die();
	//foreach($uuids as $uuid) {
	//	tic_geosource_process_record($uuid);
	//}
	tic_geosource_process_record('78f93047-74f8-4419-ac3d-fc62e4b0477b');
	die();
	
	return;
}

/**
 * Implements hook_help()
 *
 * @param current path
 * @param array 
 */
function tic_geosource_help($path, $args) {
	switch($path) {
		case "admin/help#tic_geosource":
			return '<p>' . t(' tic_geosource ') .'</p>';
			break;
	}
}

/**
 * Implements hook_menu
 */
function tic_geosource_menu() {
	$items = array();
	
	$items['tic_geosource/create_contact_ajax'] = array(
		'title' => 'Ajax backend',
		'page callback' => 'tic_geosource_addcontact_ajax_submit',
		'access callback' => true,
		'absolute' => true,
		'type' => MENU_CALLBACK,
	);
	
	$items['admin/config/services/geosource'] = array(
		'title' => 'Publication Geosource',
		'description' => 'Réglages de publication Geosource',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('tic_geosource_config'),
		'access arguments' => array('administer site configuration'),
		'file' => 'includes/tic_geosource.settings.inc',
	);
	
	$items['admin/config/services/geosource/test'] = array(
		'title' => 'Test de la configuration Geosource',
		'description' => 'Tester la configuration de Geosource',
		'page callback' => 'tic_geosource_configtest',
		'access arguments' => array('administer site configuration'),
		'file' => 'includes/tic_geosource.settings.inc',
	);
	
	return $items;
}


/**
 * Implements hook_form_alter
 *
 */
function tic_geosource_form_alter(&$form, &$form_state, $form_id) {
	
	// TODO: si edition de carte, enlever le champ 'type de carte'
	// adapter les champs en fonction du type de carte (statique ou dynamique
	if ($form_id == 'carte_node_form') {
		$form_state['no_cache'] = TRUE;
		
		drupal_add_library('system', 'ui.dialog');
		
		$form['#attached']['js'] = array(
			drupal_get_path('module', 'tic_geosource') . '/js/carto_form.js',
			drupal_get_path('module', 'tic_geosource') . '/js/chosen/chosen.jquery.min.js',
		);
		
		drupal_add_css(
			drupal_get_path('module', 'tic_geosource') . '/js/chosen/chosen.min.css',
			array('group' => CSS_THEME, 'type' => 'file')
		);
		
		$form["field_auteur"]['#suffix'] = '<a href="#" id="addContactLink">Ajouter un contact</a>';
		
		$form['#validate'][] = 'tic_geosource_form_validate';
		
		// champs non editables
		$form['field_uuid']['#access'] = FALSE;
		
		return $form;
	}
}

/**
 * Implements hook_node_validate
 */
function tic_geosource_form_validate(&$form, &$form_state) {
	//formalisme numero de carte
	//checks différents si carte statique ou dynamique
	
	drupal_add_library('system', 'ui.dialog');
	$form['#attached']['js'] = array(
		drupal_get_path('module', 'tic_geosource') . '/js/carto_form.js',
		drupal_get_path('module', 'tic_geosource') . '/js/chosen/chosen.jquery.min.js',
	);
	
	drupal_add_css(
		drupal_get_path('module', 'tic_geosource') . '/js/chosen/chosen.min.css',
		array('group' => CSS_THEME, 'type' => 'file')
	);
	
	return $form;
}

/**
 * Callback ajax de création de contact lors de la creation d'une carte
 */
function tic_geosource_addcontact_ajax_submit($form, &$form_state) {
	global $user;
	
	if (!user_access('create carto content')) {
		$ret = array('code' => 'error', 'reason' => 'Vous n\'avez pas la permission de créer des contacts');
		drupal_json_output($ret);
		drupal_exit();
	}
	
	//TODO: Verifier si les donnees sont ok et si l'email n'est pas deja utilisé
	$name = $_GET['nom'];
	$email = $_GET['email'];
	
	if (!valid_email_address($email)) {
		$ret = Array('code' => 'error', 'reason' => 'Adresse email invalide !');
		drupal_json_output($ret);
		drupal_exit();
	}
	
	// TODO: requête SQL pour vérifier que l'adresse mail est unique
	
	$contact = new StdClass();
	$contact->type = 'contact';
	$contact->title = $name;
	$contact->uid = $user->uid;
	$contact->language = LANGUAGE_NONE;
	
	//TODO: vérifier que le node a bien été sauvé; ajouter langue
	node_save($contact);
	$node_wrapper = entity_metadata_wrapper('node', $contact);
	$node_wrapper->field_adresse_email->set($email);
	$node_wrapper->save();
	
	$ret = Array('code' => 'success', 'nid' => $contact->nid, 'title' => $contact->title);
	drupal_json_output($ret);
	drupal_exit();
}

/**
 * Implements hook_node_presave
 *
 */
function tic_geosource_node_presave($node) {
	if ($node->type != 'carte') {
		return;
	}
	
	// disabled is set during cron executions
	$disabled = &drupal_static('tic_geosource_disable_geosource_push', false);
	if($disabled) {
		return;
	}
	
	if ($node->is_new) {
		$uuid = tic_geosource_insert_record($node);
		if($uuid) {
			$node->field_uuid['und'][0]['value'] = $uuid;
		}
	}
	else {
		tic_geosource_update_record($node);
	}
	
}

/**
 * Loads a CWS client
 *
 * @return cswGeoClient Instance
 */
function tic_geosource_load_csw_client() {
	//TODO: installer pear directement ?
	set_include_path(get_include_path() . PATH_SEPARATOR . dirname(__FILE__) . '/vendor');
	require_once dirname(__FILE__) . '/vendor/cswGeoClient.php';
	
	$cswServer = variable_get('geosource_server_url', '');
	$username = variable_get('geosource_server_user', '');
	$password = variable_get('geosource_server_password', '');
	$authAddress = variable_get('geosource_server_auth_address', '');
	
	if($cswServer == '') {
		return false;
	}
	
	if($authAddress != '') {
		return new cswGeoClient($cswServer, $username, $password, $authAddress);
	}
	else {
		return new cswGeoClient($cswServer);
	}
}

/**
 * Load divengine template engine (http://divengine.com)
 *
 */
function tic_geosource_load_divengine() {
	// Reconfigure div to avoid conflicts with xml language
	define('DIV_TAG_MACRO_BEGIN', '<?php');
	
	require_once dirname(__FILE__) . '/vendor/div.php';
}

/**
 * Convert a region to a bbox
 *
 * TODO: fixer les bboxs
 * @param string region
 * @return array bbox
 */
function tic_geosource_region_to_bbox($region = 'Région') {
	// default: world wide
	$bbox = Array(
		"west" => '-180',
		"east" => '180',
		"north" => '-90',
		"south" => '90',
	);
	
	switch($region) {
		case 'Europe':
			$bbox['west'] = '-18';
			$bbox['east'] = '46';
			$bbox['north'] = '71';
			$bbox['south'] = '33';
			break;
		case 'France':
			$bbox['west'] = '-6';
			$bbox['east'] = '9';
			$bbox['north'] = '51';
			$bbox['south'] = '42';
			
			break;
		case 'Région':
			$bbox['west'] = '1';
			$bbox['east'] = '5';
			$bbox['north'] = '51';
			$bbox['south'] = '49';
			
			break;
		case 'Département':
			$bbox['west'] = '1';
			$bbox['east'] = '5';
			$bbox['north'] = '51';
			$bbox['south'] = '49';
			
			break;
		case 'Infra-départemental':
			$bbox['west'] = '1';
			$bbox['east'] = '5';
			$bbox['north'] = '51';
			$bbox['south'] = '49';
			
			break;
	}
	
	return $bbox;
}


/**
 * Convert a drupal node to an array for divengine template
 *
 * @param stdClass drupal node
 * @return array paramters for divengine template
 */
function tic_geosource_drupal_node_to_geosource_array($node) {
	//load contact info
	$data = $node->field_auteur['und'][0];
	$relatedContact = node_load($data['nid']);
	
	if (isset($node->field_emprise_geographique['und'][0]['value'])) {
		$bbox = tic_geosource_region_to_bbox($node->field_emprise_geographique['und'][0]['value']);
	}
	else {
		$bbox = tic_geosource_region_to_bbox();
	}
	
	// Mots cles libres
	$keywords = array();
	if (isset($node->field_mots_cles['und'])) {
		foreach ($node->field_mots_cles['und'] as $k) {
			$keywords[] = $k['name'];
		}
	}
	
	// categorie
	$category = $node->field_categorie['und'][0]['value'];
	
	// thematiques Gemet
	$thematiques = array();
	if(isset($node->field_thematique['und'])) {
		foreach ($node->field_thematique['und'] as $t) {
			$thematiques[] = $t['value'];
		}
	}
	
	$files = array();
	
	// fichier carte
	if (isset($node->field_image_carte['und'][0]['fid'])) {
		$imageCarte = file_load($node->field_image_carte['und'][0]['fid']);
		if ($imageCarte) {
			$files[] = array(
				'name' => $imageCarte->filename,
				'url' => htmlspecialchars(file_create_url($imageCarte->uri)),
				'filetype' => $imageCarte->filemime,
				'version' => '1.0',
			);
		}
	}
	
	// image carte
	if (isset($node->field_fichier_carte['und'][0]['fid'])) {
		$fichierCarte = file_load($node->field_fichier_carte['und'][0]['fid']);
		if ($fichierCarte) {
			$files[] = array(
				'name' => $fichierCarte->filename,
				'url' => htmlspecialchars(file_create_url($fichierCarte->uri)),
				'filetype' => $fichierCarte->filemime,
				'version' => '1.0',
			);
		}
	}
	
	// imagette Remplacer par un tableau avec lien grande image et petite image
	$thumbnails = array();
	if (isset($node->field_imagette['und'][0]['fid'])) {
		$imagette = file_load($node->field_imagette['und'][0]['fid']);
		if ($imagette) {
			$thumbnails[] = array(
				'name' => $imagette->filename,
				'url' => htmlspecialchars(image_style_url('thumbnail', $imagette->uri)),
				'filetype' => $imagette->filemime,
				'description' => 'thumbnail',
			);
			$thumbnails[] = array(
				'name' => $imagette->filename,
				'url' => htmlspecialchars(image_style_url('medium', $imagette->uri)),
				'filetype' => $imagette->filemime,
				'description' => 'large_thumbnail',
			);
		}
	}
	
	if($node->is_new) {
		$uuid = false;
	}
	else {
		$uuid = $node->field_uuid['und'][0]['value'];
	}
	
	$mapUrl = '';
	if(isset($node->field_url_source_des_donnees['und'][0]['value'])) {
		$mapUrl = htmlspecialchars($node->field_url_source_des_donnees['und'][0]['value']);
	}
	
	return array(
		'language_code' => 'fre',
		'author_name' => $relatedContact->title,
		'author_organisation' => $relatedContact->title,
		'author_email' => $relatedContact->field_adresse_email['und'][0]['email'],
		//'creation_date' => '2015-11-13T08:43:18',
		'creation_date' => date("Y-m-dTH:i:s"),
		'map_title' => $node->title,
		'map_creation_date' => date("Y-m-d"),
		'map_abstract' => $node->field_description['und'][0]['value'],
		'map_purpose' => 'NONE',
		'map_number' => $node->field_numero_de_carte['und'][0]['value'], //BUG update ?
		'map_resolution' => $node->field_echelle['und'][0]['value'],
		'map_url' => $mapUrl, //BUG update ?
		'bbox' => $bbox,
		'keywords' => $keywords,
		'themes' => $thematiques,
		'category' => $category,
		'files' => $files,
		'uuid' => $uuid,
		'thumbnails' => $thumbnails,
	);
}

/**
 * Save metadata to geosource
 * 
 * @param stdClass Drupal node
 * @return string Geosource UUID
 */
function tic_geosource_insert_record($node) {
	$client = tic_geosource_load_csw_client();
	
	if ($client === false) {
		return;
	}
	
	tic_geosource_load_divengine();
	
	$template = dirname(__FILE__) . '/templates/isoRecord.tpl';
	
	$xmlString = new div($template, tic_geosource_drupal_node_to_geosource_array($node));
	//Create XML Request
	$dom = new DOMDocument('1.0');
	$dom->loadXML((string)$xmlString);
	//submit request
	try {
		$uuid = $client->insertMetadata($dom);
	}
	catch (Exception $e) {
		watchdog('tic_geosource', 'Erreur de sauvegarde de la ressource dans Geosource: '. $e->getMessage(), NULL, WATCHDOG_ERROR);
		drupal_set_message('La ressource n\'a pas été sauvée dans Geosource', 'error');
	}
	
	if(is_array($uuid)) {
		return $uuid[0];
	}
	else {
		return false;
	}
}

/**
 * Update metadata to geosource
 *
 * @param stdClass Drupal node
 * @return int number of updated records
 */
function tic_geosource_update_record($node) {
	$client = tic_geosource_load_csw_client();
	
	if($client === false) {
		return;
	}
	
	tic_geosource_load_divengine();
	
	$template = dirname(__FILE__) . '/templates/isoRecord.tpl';
	
	$xmlString = new div($template, tic_geosource_drupal_node_to_geosource_array($node));
	
	$dom = new DOMDocument('1.0');
	$dom->loadXML((string)$xmlString);	
	
	$updated = 0;
	try {
		$updated = $client->updateFullRecord($dom);
	}
	catch (Exception $e) {
		watchdog('tic_geosource', 'Erreur de mise a jour de la ressource sur Geosource: ' . $e->getMessage(), NULL, WATCHDOG_ERROR);
		drupal_set_message('La ressource n\'a pas été mise à jour dans Geosource', 'error');
	}
	
	tic_geosource_add_map_category($node);
	
	return $updated;
}

/**
 * Implements hook_cron
 *
 * TODO: vérifier que le nombre de records est bon
 *
 */
function tic_geosource_cron() {
	$last = variable_get('tic_geosource_cron_last_run', 0);
	$now = time();
	$date = new DateTime();
	$date->setTimestamp($last);
	
	// temp; avancer sur fonction record to node avant
	if($last == 0) { return; }
	
	module_load_include('inc', 'tic_geosource', 'includes/tic_geosource.utils');
	
	$client = tic_geosource_load_csw_client();
	//TODO: changes from last cron run
	$xml = $client->getRecordsModifiedSince(new DateTime('2012-07-08'));
	$records = tic_geosource_split_records($xml);
	foreach ($records as $record) {
		tic_geosource_record_to_node($record); 
	}
	
	variable_set('tic_geosource_cron_last_run', $now);
}

/**
 * Ajouter la categorie carte a l'enregistrement geosource
 *
 * @param stdClass Drupal node
 */
function tic_geosource_add_map_category($node) {
	$uuid = $node->field_uuid['und'][0]['value'];
	$client = tic_geosource_load_csw_client();
	$geoid = $client->getGeoidFromUuid($uuid);
	if($geoid) {
		return $client->addMapCategory($geoid);
	}
	
	return false;
}

/**
 * Get next map identifier
 *
 * TODO: node en paramètre pour créer la valeur a la sauvegarde ?
 * @return int identifier
 */
function tic_geosource_get_next_map_identifier() {
	$id = (int)db_query('select MAX(field_numero_de_carte_value) from field_data_field_numero_de_carte;')->fetchCol();
	
	if($id < 20000) {
		$id = 20000;
	}
	
	return $id;
}
