<?php
/**
 *
 */

// DEBUG
function tic_geosource_node_view($node, $v, $e) {
	return;
	var_dump($node); die();
	
	module_load_include('inc', 'tic_geosource', 'includes/tic_geosource.utils');
	
	//tic_geosource_load_thesaurus();
	
	//$client = tic_geosource_load_csw_client();
	//$t = $client->getGeoThemeThesaurus();
	//var_dump($t); die();
	//die();
	
	//$geoid = $client->getGeoidFromUuid('2b3bbdd1-c1b1-475a-a0c9-6478e1f949f5');
	//$client->addMapCategory($geoid);
	//die();
	
	//$xml = $client->getRecordsModifiedSince(new DateTime('2012-07-08'));
	//$uuids = tic_geosource_get_result_uuids($xml);
	
	//var_dump(tic_geosource_record_to_node($records[2])); die();
	//foreach($uuids as $uuid) {
	//	tic_geosource_process_record($uuid);
	//}
	//tic_geosource_process_record('78f93047-74f8-4419-ac3d-fc62e4b0477b');
	tic_geosource_process_record('bae9539a-e7bf-4140-b77b-0723bab82d17');
	die();
	
	return;
}

/**
 * Implements hook_cron_queue_info
 *
 */
function tic_geosource_cron_queue_info() {
	$queues['tic_geosource_sync'] = array(
		'worker callback' => 'tic_geosource_queue_worker',
		'time' => 120,
	);
	
	return $queues;
}

/**
 * Implements hook_help()
 *
 * @param current path
 * @param array 
 */
function tic_geosource_help($path, $args) {
	switch($path) {
		case "admin/help#tic_geosource":
			return '<p>' . t(' tic_geosource ') .'</p>';
			break;
	}
}

/**
 * Implements hook_menu
 */
function tic_geosource_menu() {
	$items = array();
	
	$items['tic_geosource/create_contact_ajax'] = array(
		'title' => 'Ajax backend',
		'page callback' => 'tic_geosource_addcontact_ajax_submit',
		'access callback' => true,
		'absolute' => true,
		'type' => MENU_CALLBACK,
	);
	
	$items['admin/config/services/geosource'] = array(
		'title' => 'Publication Geosource',
		'description' => 'Réglages de publication Geosource',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('tic_geosource_config'),
		'access arguments' => array('administer site configuration'),
		'file' => 'includes/tic_geosource.settings.inc',
	);
	
	$items['admin/config/services/geosource/test'] = array(
		'title' => 'Test de la configuration Geosource',
		'description' => 'Tester la configuration de Geosource',
		'page callback' => 'tic_geosource_configtest',
		'access arguments' => array('administer site configuration'),
		'file' => 'includes/tic_geosource.settings.inc',
	);
	
	return $items;
}


/**
 * Implements hook_form_alter
 *
 */
function tic_geosource_form_alter(&$form, &$form_state, $form_id) {
	
	// TODO: si edition de carte, enlever le champ 'type de carte'
	// adapter les champs en fonction du type de carte (statique ou dynamique
	if ($form_id == 'carte_node_form') {
		$form_state['no_cache'] = TRUE;
		
		drupal_add_library('system', 'ui.dialog');
		
		$form['#attached']['js'] = array(
			drupal_get_path('module', 'tic_geosource') . '/js/carto_form.js',
			drupal_get_path('module', 'tic_geosource') . '/js/chosen/chosen.jquery.min.js',
		);
		
		drupal_add_css(
			drupal_get_path('module', 'tic_geosource') . '/js/chosen/chosen.min.css',
			array('group' => CSS_THEME, 'type' => 'file')
		);
		
		$form["field_auteur"]['#suffix'] = '<a href="#" id="addContactLink">Ajouter un contact</a>';
		
		$form['#validate'][] = 'tic_geosource_form_validate';
		
		// champs non editables
		$form['field_uuid']['#access'] = FALSE;
		
		return $form;
	}
}

/**
 * Implements hook_node_validate
 */
function tic_geosource_form_validate(&$form, &$form_state) {
	//formalisme numero de carte
	//checks différents si carte statique ou dynamique
	
	drupal_add_library('system', 'ui.dialog');
	$form['#attached']['js'] = array(
		drupal_get_path('module', 'tic_geosource') . '/js/carto_form.js',
		drupal_get_path('module', 'tic_geosource') . '/js/chosen/chosen.jquery.min.js',
	);
	
	drupal_add_css(
		drupal_get_path('module', 'tic_geosource') . '/js/chosen/chosen.min.css',
		array('group' => CSS_THEME, 'type' => 'file')
	);
	
	// TODO checks particuliers dynamique / statique
	
	//statique seulement: numero de carte obligatoire
	// - pas de date de mise a jour
	// - echelle obligatoire
	// - source des données (text + date + url)
	// - collection de carte
	
	//dynamique seulement: date de mise a jour obligatoire
	// - pas de numero de carte
	// - pas d'echelle
	// - pas de source des données (texte  +date + url)
	// - pas de collection de cartes
	
	return $form;
}

/**
 * Callback ajax de création de contact lors de la creation d'une carte
 */
function tic_geosource_addcontact_ajax_submit($form, &$form_state) {
	global $user;
	
	if (!user_access('create carto content')) {
		$ret = array('code' => 'error', 'reason' => 'Vous n\'avez pas la permission de créer des contacts');
		drupal_json_output($ret);
		drupal_exit();
	}
	
	//TODO: Verifier si les donnees sont ok et si l'email n'est pas deja utilisé
	$name = $_GET['nom'];
	$email = $_GET['email'];
	
	if (!valid_email_address($email)) {
		$ret = Array('code' => 'error', 'reason' => 'Adresse email invalide !');
		drupal_json_output($ret);
		drupal_exit();
	}
	
	module_load_include('inc', 'tic_geosource', 'includes/tic_geosource.utils');
	
	$contact = tic_geosource_create_contact($name, $email);
	
	$ret = Array('code' => 'success', 'nid' => $contact->nid, 'title' => $contact->title);
	drupal_json_output($ret);
	drupal_exit();
}

/**
 * Implements hook_node_presave
 *
 */
function tic_geosource_node_presave($node) {
	if ($node->type != 'carte') {
		return;
	}
	
	// Les brouillons ne sont pas envoyés sur Geosource
	if ($node->status == 0) {
		return;
	}
	
	// disabled is set during cron executions
	$disabled = &drupal_static('tic_geosource_disable_geosource_push', false);
	if ($disabled) {
		return;
	}
	
	// a node can exists in drupal but not in geosource yet
	if (! isset($node->field_uuid['und'][0]['value'])) {
		$uuid = tic_geosource_insert_record($node);
		if ($uuid) {
			$node->field_uuid['und'][0]['value'] = $uuid;
		}
	}
	else {
		tic_geosource_update_record($node);
	}
	
}

/**
 * Loads a CWS client
 *
 * @return cswGeoClient Instance
 */
function tic_geosource_load_csw_client() {
	//TODO: installer pear directement ?
	set_include_path(get_include_path() . PATH_SEPARATOR . dirname(__FILE__) . '/vendor');
	require_once dirname(__FILE__) . '/vendor/cswGeoClient.php';
	
	$cswServer = variable_get('geosource_server_url', '');
	$username = variable_get('geosource_server_user', '');
	$password = variable_get('geosource_server_password', '');
	$authAddress = variable_get('geosource_server_auth_address', '');
	
	if ($cswServer == '') {
		return false;
	}
	
	if ($authAddress != '') {
		return new cswGeoClient($cswServer, $username, $password, $authAddress);
	}
	else {
		return new cswGeoClient($cswServer);
	}
}

/**
 * Load divengine template engine (http://divengine.com)
 *
 */
function tic_geosource_load_divengine() {
	// Reconfigure div to avoid conflicts with xml language
	define('DIV_TAG_MACRO_BEGIN', '<?php');
	
	require_once dirname(__FILE__) . '/vendor/div.php';
}

/**
 * Convert a region to a bbox
 *
 * TODO: fixer les bboxs
 * @param string region
 * @return array bbox
 */
function tic_geosource_region_to_bbox($region = 'Région') {
	// default: world wide
	$ret = Array(
		"west" => '-180',
		"east" => '180',
		"north" => '-90',
		"south" => '90',
	);
	
	$bbox = variable_get('tic_geosource_bbox');
	
	if (isset($bbox[$region])) { $ret = $bbox[$region]; }
	
	return $ret;
}

/**
 * Conversion bbox vers region
 *
 * Recupérer l'element le plus proche de la bbox de la ressource
 *
 * @param string north
 * @param string south
 * @param string east
 * @param string west
 * @return string region
 */
function tic_geosource_bbox_to_region($north, $south, $east, $west) {
	
	$north = intval($north);
	$south = intval($south);
	$east = intval($east);
	$west = intval($west);
	
	$bbox = variable_get('tic_geosource_bbox');
	
	// max value is 180. 400 will always be superior
	$northDiff = 400;
	$westDiff = 400;
	$eastDiff = 400;
	$southDiff = 400;
	
	$best = 400*4;
	$ret = '';
	
	foreach($bbox as $key => $values) {
		$ndiff = abs($north - $values['north']);
		$sdiff = abs($south - $values['south']);
		$ediff = abs($east - $values['east']);
		$wdiff = abs($west - $values['west']);
		
		$match = $ndiff + $sdiff + $ediff + $wdiff;
		if ($match < $best) {
			$best = $match;
			$ret = $key;
		}
	}
	
	return $ret;
}

/**
 * Verifier si une carte est statique ou interactive
 *
 */
function tic_geosource_is_static_map($node) {
	if ($node->field_type_de_carte['und'][0]['value'] == 'statique') {
		return true;
	}
	
	return false;
}

/**
 * Filter les entrées texte avant envoi dans Geosource
 *
 */
function tic_geosource_format_text($text) {
	return htmlspecialchars($text);
}


/**
 * Convert a drupal node to an array for divengine template
 *
 * @param stdClass drupal node
 * @return array paramters for divengine template
 */
function tic_geosource_drupal_node_to_geosource_array($node) {
	//load contact info
	$data = $node->field_auteur['und'][0];
	$relatedContact = node_load($data['nid']);
	
	// transformer la region bbox
	if (isset($node->field_emprise_geographique['und'][0]['value'])) {
		$bbox = tic_geosource_region_to_bbox($node->field_emprise_geographique['und'][0]['value']);
	}
	else { $bbox = tic_geosource_region_to_bbox(); }
	
	// Mots cles libres
	$keywords = array();
	if (isset($node->field_mots_cles['und'])) {
		foreach ($node->field_mots_cles['und'] as $k) {
			$term = taxonomy_term_load($k['tid']);
			$keywords[] = tic_geosource_format_text($term->name);
		}
	}
	
	// categorie
	$catTerm = taxonomy_term_load($node->field_categorie['und'][0]['tid']);
	$category = tic_geosource_format_text($catTerm->name);
	
	// thematiques Gemet
	$thematiques = array();
	if (isset($node->field_thematique['und'])) {
		foreach ($node->field_thematique['und'] as $t) {
			$term = taxonomy_term_load($t['tid']);
			$thematiques[] = tic_geosource_format_text($term->name);
		}
	}
	
	// fichier carte
	$files = array();
	if (isset($node->field_image_carte['und'][0]['fid'])) {
		$imageCarte = file_load($node->field_image_carte['und'][0]['fid']);
		if ($imageCarte) {
			$files[] = array(
				'name' => tic_geosource_format_text($imageCarte->filename),
				'url' => tic_geosource_format_text(file_create_url($imageCarte->uri)),
				'filetype' => tic_geosource_format_text($imageCarte->filemime),
				'version' => '1.0',
			);
		}
	}
	
	// image carte
	if (isset($node->field_fichier_carte['und'][0]['fid'])) {
		$fichierCarte = file_load($node->field_fichier_carte['und'][0]['fid']);
		if ($fichierCarte) {
			$files[] = array(
				'name' => tic_geosource_format_text($fichierCarte->filename),
				'url' => tic_geosource_format_text(file_create_url($fichierCarte->uri)),
				'filetype' => tic_geosource_format_text($fichierCarte->filemime),
				'version' => '1.0',
			);
		}
	}
	
	// imagette
	$thumbnails = array();
	if (isset($node->field_imagette['und'][0]['fid'])) {
		$imagette = file_load($node->field_imagette['und'][0]['fid']);
		if ($imagette) {
			$thumbnails[] = array(
				'name' => tic_geosource_format_text($imagette->filename),
				'url' => tic_geosource_format_text(image_style_url('thumbnail', $imagette->uri)),
				'filetype' => tic_geosource_format_text($imagette->filemime),
				'description' => 'thumbnail',
			);
			$thumbnails[] = array(
				'name' => tic_geosource_format_text($imagette->filename),
				'url' => tic_geosource_format_text(image_style_url('medium', $imagette->uri)),
				'filetype' => tic_geosource_format_text($imagette->filemime),
				'description' => 'large_thumbnail',
			);
		}
	}
	
	// UUID Geosource de la ressource (si existe)
	if (isset($node->field_uuid['und'][0]['value'])) {
		$uuid = $node->field_uuid['und'][0]['value'];
	}
	else { $uuid = false; }
	
	// Description source des données
	$sourceDesc = '';
	if (isset($node->field_source_des_donnees['und'][0]['value'])) {
		$sourceDesc = tic_geosource_format_text($node->field_source_des_donnees['und'][0]['value']);
	}
	
	// URL source des données
	$sourceUrl = '';
	if (isset($node->field_url_source_des_donnees['und'][0]['value'])) {
		$sourceUrl = tic_geosource_format_text($node->field_url_source_des_donnees['und'][0]['value']);
	}
	
	//date source des données
	$sourceDate = '';
	if (isset($node->field_date_source_des_donnees['und'][0]['value'])) {
		$sourceDate = $node->field_date_source_des_donnees['und'][0]['value'];
	}
	
	//Date de mise a jour
	if (isset($node->field_date_de_mise_jour['und'][0]['value'])) {
		$updateDate = $node->field_date_de_mise_jour['und'][0]['value'];
	}
	else { $updateDate = false; }
	
	
	// date de creation
	if (isset($node->field_date_de_realisation['und'][0]['value'])) {
		$dateRealisation = $node->field_date_de_realisation['und'][0]['value'];
	}
	else { $dateRealisation = date("Y-m-d\TH:i:s"); } 
	
	// Echelle de realisation
	$scale = '';
	if (isset($node->field_echelle['und'][0]['value'])) {
		$scale = $node->field_echelle['und'][0]['value'];
	}
	
	// URL de la carte (carte interactive)
	$mapUrl = '';
	if (isset($node->field_url_carte['und'][0]['value'])) {
		$mapUrl = $node->field_url_carte['und'][0]['value'];
	}
	
	return array(
		'language_code' => 'fre',
		'author_name' => tic_geosource_format_text($relatedContact->title),
		'author_organisation' => tic_geosource_format_text($relatedContact->title),
		'author_email' => tic_geosource_format_text($relatedContact->field_adresse_email['und'][0]['email']),
		'creation_date' => $dateRealisation,
		'update_date' => $updateDate,
		'map_title' => tic_geosource_format_text($node->title),
		'map_abstract' => tic_geosource_format_text($node->field_description['und'][0]['value']),
		'map_number' => $node->field_numero_de_carte['und'][0]['value'],
		'map_scale' => $scale,
		'source_url' => $sourceUrl,
		'source_date' => $sourceDate,
		'source_description' => $sourceDesc,
		'bbox' => $bbox,
		'keywords' => $keywords,
		'themes' => $thematiques,
		'category' => $category,
		'files' => $files,
		'uuid' => $uuid,
		'thumbnails' => $thumbnails,
		'url_carte' => $mapUrl,
	);
}

/**
 * Save metadata to geosource
 * 
 * @param stdClass Drupal node
 * @return string Geosource UUID
 */
function tic_geosource_insert_record($node) {
	
	$client = tic_geosource_load_csw_client();
	
	if ($client === false) {
		return;
	}
	
	tic_geosource_load_divengine();
	
	// TODO: template différent carte statique ou interactive
	if (tic_geosource_is_static_map($node)) {
		$template = dirname(__FILE__) . '/templates/statique.tpl';
	}
	else {
		$template = dirname(__FILE__) . '/templates/interactive.tpl';
	}
	
	$xmlString = new div($template, tic_geosource_drupal_node_to_geosource_array($node));
	//Create XML Request
	$dom = new DOMDocument('1.0');
	$dom->loadXML((string)$xmlString);
	//submit request
	try {
		$uuid = $client->insertMetadata($dom);
	}
	catch (Exception $e) {
		watchdog('tic_geosource', 'Erreur de sauvegarde de la ressource dans Geosource: '. $e->getMessage(), NULL, WATCHDOG_ERROR);
		drupal_set_message('La ressource n\'a pas été sauvée dans Geosource', 'error');
	}
	
	if (is_array($uuid)) {
		tic_geosource_add_map_category($uuid[0]);
		return $uuid[0];
	}
	else {
		return false;
	}
}

/**
 * Update metadata to geosource
 *
 * @param stdClass Drupal node
 * @return int number of updated records
 */
function tic_geosource_update_record($node) {
	$client = tic_geosource_load_csw_client();
	
	if ($client === false) {
		return;
	}
	
	tic_geosource_load_divengine();
	
	if (tic_geosource_is_static_map($node)) {
		$template = dirname(__FILE__) . '/templates/statique.tpl';
	}
	else {
		$template = dirname(__FILE__) . '/templates/interactive.tpl';
	}
	
	$xmlString = new div($template, tic_geosource_drupal_node_to_geosource_array($node));
	
	$dom = new DOMDocument('1.0');
	$dom->loadXML((string)$xmlString);
	
	$updated = 0;
	try {
		$updated = $client->updateFullRecord($dom);
	}
	catch (Exception $e) {
		watchdog('tic_geosource', 'Erreur de mise a jour de la ressource sur Geosource: ' . $e->getMessage(), NULL, WATCHDOG_ERROR);
		drupal_set_message('La ressource n\'a pas été mise à jour dans Geosource', 'error');
	}
	
	tic_geosource_add_map_category($node->field_uuid['und'][0]['value']);
	
	return $updated;
}

/*
 * Implements callback_queue_worker
 *
 * 
 */
function tic_geosource_queue_worker($uuid) {
	module_load_include('inc', 'tic_geosource', 'includes/tic_geosource.utils');
	
	tic_geosource_process_record($uuid);
}

/**
 * Implements hook_cron
 *
 */
function tic_geosource_cron() {
	$last = variable_get('tic_geosource_cron_last_run', 0);
	$delay = variable_get('geosource_sync_delay');
	$now = time();
	
	if (($now - $last) < $delay) {
		// DEBUG TODO: decommenter le return
		//return;
	}
	
	$date = new DateTime();
	$date->setTimestamp($last);
	
	module_load_include('inc', 'tic_geosource', 'includes/tic_geosource.utils');
	
	// synchro thesaurus, themes et mots cles
	tic_geosource_load_thesaurus();
	
	$client = tic_geosource_load_csw_client();
	//TODO: changes from last cron run
	$xml = $client->getRecordsModifiedSince(new DateTime('2012-07-08'));
	$uuids = tic_geosource_get_result_uuids($xml);
	
	// Ajouter les uuids a traiter dans le queue
	$queue = DrupalQueue::get('tic_geosource_sync');
	foreach ($uuids as $uuid) {
		$queue->createItem($uuid);
	}
	
	variable_set('tic_geosource_cron_last_run', $now);
}

/**
 * Ajouter la categorie carte a l'enregistrement geosource
 *
 * @param stdClass Drupal node
 */
function tic_geosource_add_map_category($uuid) {
	$client = tic_geosource_load_csw_client();
	$geoid = $client->getGeoidFromUuid($uuid);
	if ($geoid) {
		return $client->addMapCategory($geoid, array('map'));
	}
	
	return false;
}

/**
 * Get next map identifier
 *
 * TODO: node en paramètre pour créer la valeur a la sauvegarde ?
 * @return int identifier
 */
function tic_geosource_get_next_map_identifier() {
	$id = (int)db_query('select MAX(field_numero_de_carte_value) from field_data_field_numero_de_carte;')->fetchCol();
	
	if ($id < 20000) {
		$id = 20000;
	}
	
	return $id;
}
