<?php 
/**
 * TIC FILEDOWNLOAD MODULE
 *
 *
 */

/**
 * Implements hook_file_download().
 *
 * This function takes an extra parameter $field_type so that it may
 * be re-used by other File-like modules, such as Image.
 */
function tic_filedownload_file_download($uri) {
  global $user;

  // Get the file record based on the URI. If not in the database just return.
  $files = file_load_multiple(array(), array('uri' => $uri));
  if (count($files)) {
    foreach ($files as $item) {
      // Since some database servers sometimes use a case-insensitive comparison
      // by default, double check that the filename is an exact match.
      if ($item->uri === $uri) {
        $file = $item;
        break;
      }
    }
  }
  if (!isset($file)) {
    return;
  }

  $headers = file_file_download($uri);

  // Ajout du nom dans les headers pour le download
  if (isset($_REQUEST['forcedl'])) {
	  $headers['Content-Disposition'] = 'attachment; filename="'. mime_header_encode($file->filename) .'"';
  }

  return $headers;
}

